AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Multi-endpoint RAG API (Bedrock, LangChain) using AWS SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BedrockRagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.bedrock_handler
      Events:
        BedrockEndpoint:
          Type: Api
          Properties:
            Path: /rag/bedrock
            Method: post

  LangchainRagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.langchain_handler
      Events:
        LangchainEndpoint:
          Type: Api
          Properties:
            Path: /rag/langchain
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  BedrockRagFunction:
    Description: "Bedrock RAG Lambda ARN"
    Value: !GetAtt BedrockRagFunction.Arn

  LangchainRagFunction:
    Description: "LangChain RAG Lambda ARN"
    Value: !GetAtt LangchainRagFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
