name: RAGDemon deployment workflow

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

# defaults:
#   run:
#     working-directory: backend/bedrock_impl

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ragdemon-prod
          template: template.yaml
          parameter-overrides: "Environment=prod"
