# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f ./backend/requirements.txt ]; then pip install -r ./backend/requirements.txt; fi
          pip install -e ./backend
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Start FastAPI server
        env:
          OPENAI_API_KEY: ${{ secrets.TEST_API_KEY }}
          # --- prevent AWS calls in CI ---
          CHECKPOINTER_BACKEND: memory
          DEPLOY_DDB: "false"
          USER_AGENT: ragdemon-ci/1.0
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          nohup uvicorn backend.langchain_impl.src.server:api --host 127.0.0.1 --port 8000 & sleep 3
      - name: Test with pytest
        env:
          OPENAI_API_KEY: ${{ secrets.TEST_API_KEY }}
          # --- prevent AWS calls in CI ---
          CHECKPOINTER_BACKEND: memory
          DEPLOY_DDB: "false"
          USER_AGENT: ragdemon-ci/1.0
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          pytest || [ $? -eq 5 ]
